account/urls.py
from django.urls import path, include
from .views import \
    register

app_name= "account"
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
]

blog/urls.py
# blog/urls.py

from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_index, name="dashboard"),
    path("post/<int:pk>/", views.blog_detail, name="detail"),
    path("category/<category>/", views.blog_category, name="category"),
]

pet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace="account")),
    path("", include("blog.urls", namespace="blog")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )
    date_of_birth = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'Profile of {self.user.username}'

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField("Category", related_name="posts")

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    text = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} on '{self.post}'"

account/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

from account.models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Repeat password',
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data

        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError('Email already in use')


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def clean_email(self):
        new_email = self.cleaned_data['email']

        if new_email == '' or new_email == self.instance.email:
            return
        if User.objects.filter(email=new_email).exists():
            raise forms.ValidationError('Email already in use')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth']

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text' : 'Your Comment'}

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            # Customize the form widget attributes if needed
            self.fields['text'].widget.attrs.update({'class': 'form-control', 'rows': 4})

account/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST

from .forms import \
    LoginForm, \
    UserRegisterForm, \
    UserEditForm, \
    ProfileEditForm

from .models import Profile


def register(request):
    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)

            new_user.set_password(
                user_form.cleaned_data['password']
            )

            new_user.save()

            Profile.objects.create(user=new_user)

            return render(request, 'registration/login.html')
            # return render(request, 'account/register_done.html', context={'new_user': new_user})
    else:
        user_form = UserRegisterForm()
    return render(request, 'account/register.html', context={'form': user_form})


# @login_required
# def edit_profile(request):
#     is_edited = None
#     if request.method == 'POST':
#         user_form = UserEditForm(
#             instance=request.user,
#             data=request.POST
#         )
#         profile_form = ProfileEditForm(
#             instance=request.user.profile,
#             data=request.POST,
#         )
#
#         if user_form.is_valid() and profile_form.is_valid():
#             is_edited = True
#             user_form.save()
#             profile_form.save()
#             messages.success(request, 'Your profile has been updated successfully')
#         else:
#             messages.error(request, 'Error occured while updating your profile')
#     else:
#         user_form = UserEditForm(instance=request.user)
#         profile_form = ProfileEditForm(instance=request.user.profile)
#
#     return render(request, 'account/../templates/registration/edit.html', context={
#         "user_form": user_form,
#         "profile_form": profile_form,
#         "is_edited": is_edited
#     })

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Comment
from blog.forms import CommentForm

def blog_index(request):
    posts = Post.objects.all().order_by("-created_on")
    context = {
        "posts": posts,
    }
    return render(request, "blog/index.html", context)

def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by("-created_on")
    context = {
        "category": category,
        "posts": posts,
    }
    return render(request, "blog/category.html", context)

def blog_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment = Comment.objects.filter(post=post)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            return redirect('blog:detail', pk = pk)
    else:
        Comment_form = CommentForm()

    context = {
        "post" : post,
        "comment" : comment,
        "form" : Comment_form,
    }
    return render(request, "blog/detail.html", context)

blog/templates/blog/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>My Personal Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
</head>
<body>
<h1>Timur Tynychbekov's Weblog</h1>
<a href="{% url "blog:blog_index" %}">Home</a>

<div class="auth-section">
    {% if user.is_authenticated %}
        <p>Welcome, <span class="username">{{ user.username }}</span>! <a href="{% url 'blog:logout' %}">Logout</a></p>
    {% else %}
        <p><a href="{% url 'blog:login' %}">Login</a></p>
    {% endif %}
</div>

<hr>
{% block page_title %}{% endblock page_title %}

{% block page_content %}{% endblock page_content %}
</body>
</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block page_title %}
    <h2 class="mb-3">{{ post.title }}</h2>
{% endblock page_title %}

{% block page_content %}
    <div class="container post">
        <p class="text-muted">
            {{ post.created_on.date }} | Categories:
            {% for category in post.categories.all %}
                <span class="badge badge-info">
                    <a href="{% url 'blog_category' category.name %}" class="text-white">
                        {{ category.name }}
                    </a>
                </span>
            {% endfor %}
        </p>

        <div class="detail">
            <p class="mb-4">{{ post.body | linebreaks }}</p>
        </div>

        <div class="comments-section">
            <h2>Comments</h2>
            <ul class="comments-list list-unstyled">
                {% for com in comment %}
                    <li class="mb-3">
                        <div class="comment-header">
                            <strong>{{ com.user.username }}</strong>
                            <span class="text-muted">{{ com.created_at | date:'F d, Y H:i' }}</span>
                        </div>
                        <p>{{ com.text }}</p>
                    </li>
                {% endfor %}
            </ul>

            <div class="add-comment-form">
                <h2>Add a Comment</h2>
                <form method="post" action="{% url 'blog_detail' post.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Add Comment</button>
                </form>
            </div>
        </div>
    </div>
{% endblock page_content %}

blog/templates/blog/index.html
<!-- blog/templates/blog/index.html -->
{% extends "blog/base.html" %}
{% block page_title %}
    <h2>All Posts</h2>
{% endblock page_title %}

{% block page_content %}
    {% block posts  %}
        {% for post in posts %}
            <article class="post">
            <h3><a href="{% url 'blog:blog_detail' post.pk %}">{{ post.title }}</a></h3>
            <small>
                {{ post.created_on.date }} | Categories:
                {% for category in post.categories.all %}
                    <a href="{% url 'blog:blog_category' category.name %}">
                        {{ category.name }}
                    </a>

                {% endfor %}
            </small>
            <p>{{ post.body | slice:":400" }}...</p>
            </article>
        {% endfor %}
    {% endblock posts %}
{% endblock page_content %}

templates/blog/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>My Personal Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
</head>
<body>
<h1>Timur Tynychbekov's Weblog</h1>
<a href="{% url "blog:dashboard" %}">Home</a>

<div class="auth-section">
    {% if user.is_authenticated %}
        <p>Welcome, <span class="username">{{ user.username }}</span>! </p>
        <form action="{% url "account:logout" %}" method="post" id="logout_form">
            {% csrf_token %}
            <input type="submit" value="Logout now" />
        </form>
    {% else %}
        <p><a href="{% url 'account:login' %}">Login</a></p>
    {% endif %}
</div>

<hr>
{% block page_title %}{% endblock page_title %}

{% block page_content %}{% endblock page_content %}
</body>
</html>

templates/blog/category.html
<!-- blog/templates/blog/category.html -->

{% extends "blog/index.html" %}

{% block page_title %}
<h2>{{ category }}</h2>
{% endblock page_title %}

templates/blog/detail.html
{% extends "blog/base.html" %}

{% block page_title %}
    <h2 class="mb-3">{{ post.title }}</h2>
{% endblock page_title %}

{% block page_content %}
    <div class="container post">
        <p class="text-muted">
            {{ post.created_on.date }} | Categories:
            {% for category in post.categories.all %}
                <span class="badge badge-info">
                    <a href="{% url 'blog:category' category.name %}" class="text-white">
                        {{ category.name }}
                    </a>
                </span>
            {% endfor %}
        </p>

        <div class="detail">
            <p class="mb-4">{{ post.body | linebreaks }}</p>
        </div>

        <div class="comments-section">
            <h2>Comments</h2>
            <ul class="comments-list list-unstyled">
                {% for com in comment %}
                    <li class="mb-3">
                        <div class="comment-header">
                            <strong>{{ com.user.username }}</strong>
                            <span class="text-muted">{{ com.created_at | date:'F d, Y H:i' }}</span>
                        </div>
                        <p>{{ com.text }}</p>
                    </li>
                {% endfor %}
            </ul>

            <div class="add-comment-form">
                <h2>Add a Comment</h2>
                <form method="post" action="{% url 'blog:detail' post.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Add Comment</button>
                </form>
            </div>
        </div>
    </div>
{% endblock page_content %}

templates/blog/index.html
<!-- blog/templates/blog/index.html -->
{% extends "blog/base.html" %}
{% block page_title %}
    <h2>All Posts</h2>
{% endblock page_title %}

{% block page_content %}
    {% block posts  %}
        {% for post in posts %}
            <article class="post">
            <h3><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></h3>
            <small>
                {{ post.created_on.date }} | Categories:
                {% for category in post.categories.all %}
                    <a href="{% url 'blog:category' category.name %}">
                        {{ category.name }}
                    </a>

                {% endfor %}
            </small>
            <p>{{ post.body | slice:":400" }}...</p>
            </article>
        {% endfor %}
    {% endblock posts %}
{% endblock page_content %}

templates/blog/profile.html
<!-- templates/profile.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>User Profile</h2>
  <p>Username: {{ user_profile.user.username }}</p>
  <p>Bio: {{ user_profile.bio }}</p>
  <p>Birth Date: {{ user_profile.birth_date }}</p>
  <!-- Add other profile information here -->

  <!-- Example: Display the profile picture if available -->
  {% if user_profile.profile_picture %}
    <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
  {% endif %}
{% endblock %}